export const BUILTIN_REVIEW_WEIGHTS = {
  schemaVersion: 1,
  modelType: "linear-review-ranker-v1",
  modelName: "builtin-default",
  createdAt: "2026-04-22T00:00:00.000Z",
  sourceSummary: "Built-in default review model weights",
  intercept: 0,
  gateThresholds: {
    maxDurationDeltaSec: 0.05,
    maxOffsetSec: 0.08,
    minOffsetConfidence: 0.35,
    maxPeakDb: -1.5,
    maxEndFadeRisk: 0.62,
    maxOverallRiskDelta: 0.08,
    maxInstabilityDelta: 0.06,
    maxSentenceJumpDelta: 0.05,
    maxPauseNoiseRiskDelta: 0.05,
    maxCompressionDelta: 0.06,
    maxEchoDelta: 0.05,
    maxClickDelta: 0.05,
    maxSibilanceDelta: 0.05,
    maxPauseNoiseFloorLiftDb: 1.0,
    maxNoiseContrastLossDb: 2.0,
  },
  penaltyWeights: {
    durationMismatch: 5200,
    offsetMismatch: 2600,
    peakViolation: 900,
    endingDamage: 1400,
    sourceRegression: 850,
  },
  featureWeights: {
    baseline_total: 0,
    baseline_stability: 18,
    baseline_pause: 9,
    baseline_compression: 7,
    baseline_echo: 5,
    candidate_overallRisk: 26,
    candidate_instabilityScore: 14,
    candidate_sentenceJumpScore: 14,
    candidate_pauseNoiseRisk: 11,
    candidate_compressionScore: 10,
    candidate_echoScore: 9,
    candidate_clickScore: 10,
    candidate_endFadeRiskScore: 12,
    candidate_sibilanceScore: 8,
    delta_overallRisk: 24,
    delta_instabilityScore: 16,
    delta_sentenceJumpScore: 16,
    delta_pauseNoiseRisk: 12,
    delta_compressionScore: 10,
    delta_echoScore: 10,
    delta_clickScore: 10,
    delta_endFadeRiskScore: 15,
    delta_sibilanceScore: 8,
    delta_pauseNoiseFloorDb: 6,
    delta_noiseContrastDb: -2,
    alignment_durationDeltaSec: 40,
    alignment_offsetSec: 55,
    alignment_offsetConfidence: -4,
    candidate_peakOverLimitDb: 16,
    healthy_segmented_bonus: -0.12,
    degraded_penalty: 0.2,
  },
} as const;
