import { promises as fs } from "node:fs";
import path from "node:path";
import { parseLearnedReviewWeights, type ReviewTrainingReport } from "../src/lib/reviewLearning.ts";

type CliArgs = {
  weightsPath: string;
  reportPath: string | null;
  targetPath: string;
};

const usage = () =>
  [
    "Usage:",
    "  npm run promote:review-model -- --weights <review-weights.json> [--report <review-training-report.json>] [--target <src/lib/defaultReviewWeights.ts>]",
  ].join("\n");

const parseArgs = (argv: string[]): CliArgs => {
  let weightsPath = "";
  let reportPath: string | null = null;
  let targetPath = path.resolve(process.cwd(), "src/lib/defaultReviewWeights.ts");

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--weights") {
      weightsPath = argv[index + 1] ?? "";
      index += 1;
    } else if (arg === "--report") {
      reportPath = path.resolve(process.cwd(), argv[index + 1] ?? "");
      index += 1;
    } else if (arg === "--target") {
      targetPath = path.resolve(process.cwd(), argv[index + 1] ?? "");
      index += 1;
    }
  }

  if (!weightsPath) {
    throw new Error(usage());
  }

  return {
    weightsPath: path.resolve(process.cwd(), weightsPath),
    reportPath,
    targetPath,
  };
};

const buildSourceFile = (weights: unknown) =>
  [
    "// Auto-generated by `npm run promote:review-model`.",
    "// Commit this file to ship the trained review model as the new built-in default for all users.",
    `export const BUILTIN_REVIEW_WEIGHTS = ${JSON.stringify(weights, null, 2)} as const;`,
    "",
  ].join("\n");

const main = async () => {
  const args = parseArgs(process.argv.slice(2));
  const rawWeights = JSON.parse(await fs.readFile(args.weightsPath, "utf8"));
  const weights = parseLearnedReviewWeights(rawWeights);
  if (!weights) {
    throw new Error("Invalid review-weights.json file.");
  }

  let report: ReviewTrainingReport | null = null;
  if (args.reportPath) {
    report = JSON.parse(await fs.readFile(args.reportPath, "utf8")) as ReviewTrainingReport;
  }

  await fs.mkdir(path.dirname(args.targetPath), { recursive: true });
  await fs.writeFile(args.targetPath, buildSourceFile(weights), "utf8");

  console.log(`Promoted review model: ${weights.modelName}`);
  console.log(`Updated built-in defaults: ${args.targetPath}`);
  if (report) {
    console.log(
      [
        `Reviewed bundles: ${report.reviewedBundleCount}`,
        `Pairwise examples: ${report.pairwiseExampleCount}`,
        `Pairwise accuracy: ${report.pairwiseAccuracy === null ? "n/a" : `${(report.pairwiseAccuracy * 100).toFixed(1)}%`}`,
        `Failed reviews: ${report.failedReviews}`,
      ].join("\n"),
    );
  }
  console.log("Next step: commit the updated built-in weights and deploy.");
};

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
